name: Build and Release

on:
  push:
    branches: 
    tags:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential 

      - name: Build project
        run: |
          mkdir -p build
          cd build 
          cmake .. 
          make 

      - name: Archive Executable 
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          mkdir -p dist
          cp ./build/zwave_nvm_tool dist/
          cd dist 
          tar -czvf ../${REPO_NAME}-${TAG_NAME}.tar.gz *

      - name: Create GitHub Release
        env:
          token-defined: ${{ secrets.GITHUB_TOKEN != '' }}
          REPO_NAME: ${GITHUB_REPOSITORY#*/}
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' && contains( github.ref, 'refs/tags/' ) }}
        with:
          files: ./*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

